spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&allowMultiQueries=true
    username: root
    password: root
  jpa:
      hibernate:
        ddl-auto: update
      show-sql: true

  redis:
    host: 127.0.0.1
    port: 6379
    password:
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 500

  thymeleaf:
    prefix: classpath:/templates/html/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    cache: false

  mail:
    default-encoding: UTF-8
    host: smtp.qq.com
    protocol: smtp
    username: 1140867582@qq.com
    password: cxvyyyphryozhjfe

  smtp:
    auth: true
    starttls:
      enable: true
      required: true

mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml
  type-aliases-package: com.yidiandian.entity


